version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    ports:
    - 9200:9200
    environment:
      - cluster.name=predictionio
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  pio:
    build: .
    image: predictionio
    depends_on:
    - elasticsearch
    volumes:
    - ./files/pio-env.sh:/opt/pio/conf/pio-env.sh:ro
    ports:
    - 8000:8000
    - 7070:7070